# coding: utf-8

"""
    CopycatDog API with OpenAPI 3

    CopycatDog copies a static web page (e.g. created via Wordpress or Webflow) to an S3 bucket from where you can host your page.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def copy_to_s3_get(self, s3_bucket_id, website_url, **kwargs):  # noqa: E501
        """Copies a website to a specified AWS S3 bucket.  # noqa: E501

        There\\'s a lot more to says about this endpoint **but** we\\'ll keep it short for now.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.copy_to_s3_get(s3_bucket_id, website_url, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str s3_bucket_id: Your AWS S3 bucket ID where you want to store the website to be copied. (required)
        :param str website_url: The full website URL to be copied. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.copy_to_s3_get_with_http_info(s3_bucket_id, website_url, **kwargs)  # noqa: E501
        else:
            (data) = self.copy_to_s3_get_with_http_info(s3_bucket_id, website_url, **kwargs)  # noqa: E501
            return data

    def copy_to_s3_get_with_http_info(self, s3_bucket_id, website_url, **kwargs):  # noqa: E501
        """Copies a website to a specified AWS S3 bucket.  # noqa: E501

        There\\'s a lot more to says about this endpoint **but** we\\'ll keep it short for now.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.copy_to_s3_get_with_http_info(s3_bucket_id, website_url, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str s3_bucket_id: Your AWS S3 bucket ID where you want to store the website to be copied. (required)
        :param str website_url: The full website URL to be copied. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['s3_bucket_id', 'website_url']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method copy_to_s3_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 's3_bucket_id' is set
        if ('s3_bucket_id' not in params or
                params['s3_bucket_id'] is None):
            raise ValueError("Missing the required parameter `s3_bucket_id` when calling `copy_to_s3_get`")  # noqa: E501
        # verify the required parameter 'website_url' is set
        if ('website_url' not in params or
                params['website_url'] is None):
            raise ValueError("Missing the required parameter `website_url` when calling `copy_to_s3_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 's3_bucket_id' in params:
            query_params.append(('s3BucketId', params['s3_bucket_id']))  # noqa: E501
        if 'website_url' in params:
            query_params.append(('websiteUrl', params['website_url']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/copyToS3', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
