# coding: utf-8

# flake8: noqa
"""
    CopycatDog API with OpenAPI 3

    CopycatDog copies a static web page (e.g. created via Wordpress or Webflow) to an S3 bucket from where you can host your page.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
