# coding: utf-8

"""
    CopycatDog API with OpenAPI 3

    CopycatDog copies a static web page (e.g. created via Wordpress or Webflow) to an S3 bucket from where you can host your page.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_copy_to_s3_get(self):
        """Test case for copy_to_s3_get

        Copies a website to a specified AWS S3 bucket.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
