=begin
CopycatDog API

CopycatDog copies a static web page (e.g. created via Wordpress or Webflow) to an S3 bucket from where you can host your page.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration
  def change
  end
end
